"use client"
import Navigation from "@ui/components/Navigation"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { QueryClientProvider, QueryClient } from "@tanstack/react-query"
import { AuthProvider } from "react-auth-kit"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

const queryClient = new QueryClient()

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <AuthProvider
          authType="cookie"
          authName="_auth"
          cookieDomain={window.location.hostname}
          cookieSecure={false}
        >
          <QueryClientProvider client={queryClient}>
            {children}
          </QueryClientProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
